version: '3.7'

services:
  postgres:
    image: postgres:12
    restart: always
    hostname: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env.development
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
