version: '3.7'

services:
  postgres:
    image: postgres:12
    restart: always
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - '6379:6379'

  ohbug-ce:
    image: ohbug/ohbug-ce:latest
    restart: always
    volumes:
      - /usr/src/ohbug
    ports:
      - 6660:6660
      - 80:80
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
