version: '3.7'

services:
  ohbug-ce:
    image: ohbug/ohbug-ce:latest
    restart: always
    env_file:
      - ../.env.production
    volumes:
      - /usr/src/app
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 6660:6660
      - 6666:6666
      - 80:80
      - 443:443
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  postgres:
    image: postgres:12
    restart: always
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ohbug
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ohbug_postgres_password
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.0.1
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./temp/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

volumes:
  pgdata:
